In [1]:
from datasets import load_dataset 

# Example 1: Load the Protein nodes
proteins = load_dataset("HUBioDataLab/CROssBARv2-KG", data_files="nodes/Protein.csv")

# Example 2: Load Drug-Target Interactions (Edges)
dti = load_dataset("HUBioDataLab/CROssBARv2-KG", data_files="edges/DTI.csv")

/opt/miniconda3/envs/hyper-crossbar/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

'\nprint(proteins)\nprint(proteins["train"].column_names)\nprint(proteins["train"][0])\n\nprint(dti)\nprint(dti["train"].column_names)\nprint(dti["train"][0])\n\n# convert to pandas\n\nprotein_df = proteins["train"].to_pandas()\ndti_df = dti["train"].to_pandas()\n\nprint(protein_df.head())\nprint(dti_df.head())\nprint(dti_df.columns)\nprint(dti_df.isna().sum())\n'

In [2]:
print(proteins)

DatasetDict({
    train: Dataset({
        features: ['id', 'length', 'mass', 'organism_name', 'organism_id', 'primary_protein_name', 'protein_names', 'xref_proteomes', 'sequence', 'prott5_embedding', 'source', 'licence', 'version'],
        num_rows: 461775
    })
})

In [4]:
proteins["train"][0]

{'id': 'uniprot:P81730',
 'length': 119,
 'mass': 12555,
 'organism_name': 'Achromobacter lyticus',
 'organism_id': 224,
 'primary_protein_name': 'Achromolysin',
 'protein_names': "['Achromolysin']",
 'xref_proteomes': None,
 'sequence': 'AQVGTGPGGNQKIGQYEYGSGGRPFLDVAQSGSTYTFNTTNLTVNLNHGTSGSTAYSYTGPRNTINGAYSPLNDAHYFGRDYWTPSTNFNQGGQGVRQAAADLGYSTADVIDAFRQVGV',
 'prott5_embedding': "['0.05215', '-0.03632', '-0.0495', '0.02155', '0.00476', '0.0953', '-0.00261', '-0.0368', '0.06122', '0.010345', '-0.05185', '0.02979', '0.012375', '0.02388', '0.00452', '0.0012045', '-0.04758', '-0.0879', '-0.02022', '0.02205', '-0.014854', '0.04703', '-0.1188', '0.07904', '0.02039', '0.0791', '-0.0495', '-0.1083', '0.006916', '0.0329', '0.01993', '0.05725', '-0.1512', '0.02905', '-0.1191', '0.0965', '-0.02379', '0.076', '-0.01529', '0.05972', '0.0134', '-0.054', '-0.08405', '0.004967', '0.02232', '-0.0819', '-0.01243', '0.1256', '0.01065', '0.007378', '-0.003538', '-0.0711', '0.02681', '-0.07697', '-0.02309', '0.02057', '-0.014946', '-0.0528', '-0.096', '-0.06146', '-0.004963', '-0.00713', '-0.02618', '0.02235', '-0.03647', '0.1392', '-0.001334', '0.05405', '0.04846', '-0.0786', '-0.002047', '-0.1362', '-0.1279', '-0.0895', '-0.0441', '0.02664', '0.03256', '-0.06015', '0.0518', '-0.02585', '-0.01538', '-0.0667', '-0.04312', '0.0355', '-0.02216', '-0.0561', '-0.0262', '-0.02466', '-0.0495', '-0.014565', '-0.04538', '-0.02786', '0.03912', '-0.03085', '-0.006348', '-0.006485', '-0.097', '-0.0939', '-0.0727', '0.005993', '-0.0532', '0.02573', '0.05206', '0.0199', '0.06085', '-0.01253', '0.02841', '-0.12476', '0.03586', '-0.05634', '0.03467', '0.0498', '0.00847', '-0.03946', '0.01952', '0.02934', '0.04446', '0.0008597', '-0.0344', '0.05145', '-0.0263', '-0.02267', '0.03333', '0.02347', '0.05356', '-0.04984', '-0.02089', '-0.0337', '0.05768', '0.02748', '0.08746', '0.0488', '0.01646', '-0.005882', '-0.05316', '0.0422', '-0.0361', '-0.08624', '0.007103', '-0.00010175', '0.03183', '0.01987', '0.05875', '-0.00607', '-0.1005', '0.05203', '-0.09753', '-0.02168', '0.0794', '0.03433', '0.0272', '0.05136', '0.08777', '-0.03818', '0.02', '-0.02463', '-0.0976', '-0.02707', '-0.06726', '-0.000737', '-0.000349', '-0.01078', '0.00582', '0.03613', '-0.01549', '0.06647', '0.02959', '0.05823', '-0.03738', '-0.02306', '0.0566', '0.04135', '0.05075', '0.10333', '-0.02733', '0.07904', '-0.009575', '-0.06775', '-0.03204', '0.0691', '-0.0346', '-0.053', '-0.01794', '0.007694', '-0.00749', '-0.078', '-0.02539', '-0.0733', '0.04108', '0.03195', '-0.053', '-0.03696', '-0.01035', '0.0394', '-0.04364', '-0.0729', '-0.0518', '-0.02533', '0.05167', '-0.01216', '-0.07837', '-0.003342', '0.001888', '-0.03238', '0.02122', '-0.03226', '0.0403', '-0.00062', '-0.03357', '-0.01738', '0.008415', '-0.11786', '0.04837', '-0.009514', '-0.0374', '0.05087', '-0.0241', '-0.0729', '-0.0293', '-0.04102', '0.01466', '0.0005183', '-0.02773', '-0.04953', '0.03836', '0.04645', '-0.0327', '0.01685', '0.0628', '-0.04462', '0.04465', '0.0018015', '-0.1526', '-0.03168', '-0.02147', '-0.00478', '-0.0979', '-0.011826', '-0.0598', '0.02196', '-0.006836', '0.0947', '0.002377', '0.0602', '-0.04913', '0.0999', '0.04535', '-0.03061', '0.1775', '-0.002035', '-0.03906', '-0.0303', '0.0214', '-0.05386', '-0.0289', '-0.03723', '0.06134', '0.06015', '-0.01338', '-0.0247', '0.02129', '-0.0721', '0.058', '0.02371', '-0.05777', '-0.0652', '-0.009636', '0.03035', '-0.0666', '-0.05585', '0.004074', '-0.09534', '0.05582', '-0.1243', '-0.03674', '-0.1034', '0.01694', '-0.000445', '0.06415', '-0.000608', '-0.003902', '-0.101', '-0.01309', '-0.06384', '0.00853', '-9.97e-05', '0.0122', '-0.02284', '0.03015', '-0.004128', '-0.005806', '0.0517', '-0.005386', '0.02379', '0.0548', '-0.003004', '0.0944', '-0.03918', '0.0806', '-0.0965', '0.08014', '0.0313', '0.04138', '0.002907', '0.0677', '0.00945', '0.03735', '-0.06433', '0.004364', '0.0383', '0.05948', '-0.01878', '0.007114', '-0.06604', '-0.02449', '-0.10535', '-0.0707', '0.06616', '0.1592', '-0.0244', '0.011696', '0.0213', '0.09534', '0.0347', '-0.06067', '0.05603', '-0.1057', '-0.08057', '0.05096', '0.02939', '0.00983', '-0.01454', '-0.005466', '0.03023', '-0.01041', '-0.02898', '-0.06256', '-0.005157', '-0.02994', '-0.00965', '-0.0464', '-0.03427', '0.009895', '0.01753', '0.10345', '-0.00811', '-0.03323', '0.03818', '-0.0528', '0.08844', '0.0383', '-0.04492', '-0.0059', '-0.03488', '0.06287', '-0.02856', '-0.03323', '-0.005405', '-0.09247', '0.05267', '-0.0601', '0.0508', '-0.04788', '0.05124', '-0.02113', '-0.2047', '-0.05872', '-0.0312', '-0.04236', '-0.006737', '-0.006096', '-0.0543', '-0.04025', '0.08435', '-0.01913', '-0.03998', '-0.01559', '-0.0543', '-0.06134', '0.02591', '-0.0696', '-0.02701', '-0.05078', '0.0628', '-0.02052', '-0.07117', '-0.0656', '0.12366', '0.0045', '-0.0082', '-0.0226', '0.01109', '0.02596', '-0.0969', '-0.00438', '0.0913', '-0.0006785', '-0.01672', '0.02477', '-0.0005975', '0.03995', '-0.0317', '-0.01533', '0.1168', '-0.0674', '-0.12274', '-0.0367', '0.1116', '0.0333', '-0.0644', '-0.03857', '0.0374', '-0.0358', '0.05774', '0.0002084', '0.06445', '0.0617', '0.08716', '0.01121', '0.02347', '-0.0191', '0.01749', '0.0335', '-0.06476', '-0.02684', '0.00656', '0.04117', '0.02222', '-0.003687', '0.0476', '-0.00665', '0.002771', '-0.00756', '-0.0741', '0.012535', '-0.04858', '0.1028', '0.1633', '-0.0668', '0.05182', '0.000976', '-0.015205', '0.0707', '0.1334', '0.0224', '-0.02284', '-0.002869', '-0.00963', '-0.004448', '-0.01576', '0.02765', '0.00971', '0.05362', '0.1109', '-0.03433', '-0.07916', '0.04483', '-0.02536', '-0.004467', '0.03604', '0.0716', '0.05078', '0.0645', '0.0983', '0.03983', '-0.0662', '0.145', '0.06836', '0.0799', '-0.09094', '0.01472', '0.06287', '0.0396', '0.02017', '0.03687', '0.02579', '0.04584', '0.08673', '0.088', '-0.02081', '0.04242', '-0.02856', '0.02318', '-0.01648', '-0.08386', '-0.1045', '-0.01164', '0.02597', '-0.0503', '-0.007545', '-0.003712', '0.02405', '-0.004444', '-0.01747', '0.0943', '0.00669', '-0.02158', '-0.0716', '0.1191', '-0.1283', '0.01573', '-0.01755', '0.03314', '-0.05063', '-0.1326', '0.03075', '-0.06186', '0.02309', '0.0712', '0.01616', '-0.03497', '0.00765', '0.03702', '-0.02266', '-0.001959', '-0.04413', '0.00943', '0.0815', '0.08057', '0.02264', '-0.01935', '0.03723', '0.000866', '-0.03168', '-0.02457', '-0.1522', '-0.04584', '-0.007534', '0.0306', '-0.1247', '-0.05765', '-0.001104', '0.0788', '-0.04214', '-0.0007315', '-0.11475', '-0.04922', '0.0832', '-0.00792', '0.08405', '-0.01836', '0.0096', '-0.05502', '-0.001283', '-0.05725', '-0.1136', '0.05893', '-0.04095', '0.02025', '-0.002', '-0.0819', '0.06085', '0.0006166', '-0.03293', '0.0923', '0.01271', '0.006577', '0.0784', '0.01883', '0.02353', '-0.05533', '0.015', '0.0244', '0.0186', '-0.02647', '0.0638', '-0.07715', '0.00237', '0.002945', '0.03793', '-0.02791', '-0.04944', '0.03256', '-0.04794', '0.05786', '-0.02899', '-0.03317', '-5.186e-05', '-0.03287', '0.03827', '0.02954', '0.05933', '-0.03885', '-0.0748', '0.006413', '0.02934', '0.00464', '-0.01319', '0.04343', '-0.0487', '-0.003246', '0.0372', '0.0827', '-0.0475', '0.04767', '0.01991', '-0.005642', '0.01237', '-0.03702', '-0.02559', '-0.02237', '0.02567', '-0.003876', '-0.02367', '0.08966', '0.01836', '-0.01544', '-0.02757', '-0.05286', '0.01808', '0.0299', '-0.01607', '0.02243', '-0.0433', '0.0644', '0.1599', '-0.01642', '0.0435', '0.1714', '0.1032', '-0.08453', '0.0571', '0.0276', '-0.03494', '-0.06616', '-0.04776', '-0.06366', '-0.01732', '0.04092', '0.02051', '0.01387', '-0.07086', '-0.04126', '0.04095', '0.0384', '0.003014', '-0.03091', '0.013214', '0.02596', '0.005398', '0.03111', '0.02875', '-0.0354', '0.05347', '0.08795', '0.00558', '0.0192', '-0.02583', '-0.0954', '0.013054', '-0.01112', '0.04333', '-0.02808', '0.0569', '0.02107', '-0.02347', '0.08514', '0.03247', '0.02374', '-0.03983', '0.03302', '-0.04242', '0.0555', '-0.0008044', '0.00494', '-0.03375', '-0.0463', '-0.010315', '0.007587', '0.08026', '0.03088', '-0.01654', '-0.00149', '0.04453', '-0.0349', '-0.0863', '-0.011475', '0.02641', '0.007435', '-0.006165', '0.0388', '-0.0164', '-0.008736', '0.0733', '0.02847', '0.00921', '-0.023', '0.00315', '0.05765', '-0.1351', '-0.091', '-0.00931', '-0.02164', '0.01546', '-0.05817', '0.0363', '0.01872', '0.01794', '-0.0467', '-0.02173', '0.01116', '0.04938', '-0.0458', '-0.01462', '-0.0515', '0.06128', '-0.09485', '0.05728', '-0.01854', '0.01707', '-0.03662', '0.02475', '0.02', '-0.001915', '-0.04288', '-0.1016', '-0.02283', '-0.01955', '0.02658', '-0.00923', '-0.001794', '-0.03986', '-0.0477', '0.116', '-0.04745', '-0.038', '-0.003122', '-0.03674', '-0.02348', '-0.01724', '-0.0862', '-0.03885', '0.01932', '-0.11444', '0.01813', '0.03235', '-0.0275', '-0.06384', '-0.0326', '0.0622', '-0.01917', '-0.03125', '-0.0798', '0.03687', '0.0837', '-0.0824', '-0.06003', '-0.05304', '-0.03995', '-0.0662', '0.02464', '0.07477', '-0.05347', '-0.02032', '0.01028', '0.0541', '-0.02055', '-0.06174', '-0.06964', '0.03842', '0.02582', '0.06506', '-0.1349', '0.073', '-0.0406', '0.01904', '0.001884', '-0.01852', '0.003841', '-0.005676', '0.04248', '-0.04596', '-0.0679', '0.0573', '-0.002823', '0.03091', '-0.06003', '-0.00136', '-0.03784', '-0.1599', '-0.03223', '-0.01768', '-0.011116', '0.06866', '0.03485', '0.02255', '0.02501', '-0.05032', '-0.01585', '0.04114', '0.00963', '0.0571', '-0.07007', '0.0294', '-0.0789', '0.03308', '0.04523', '0.10645', '-0.05096', '0.007053', '0.00869', '0.0571', '-0.07324', '0.0751', '-0.03467', '-0.0418', '-0.0131', '0.02147', '0.00762', '-0.01678', '-0.05624', '0.01157', '0.05853', '-0.013916', '0.10693', '0.002121', '-0.01347', '-0.1036', '-0.001761', '-0.003155', '0.0678', '0.01912', '0.04306', '0.0382', '0.02106', '0.02397', '0.05264', '0.01701', '-0.01072', '0.0414', '0.01037', '-0.01703', '-0.1027', '0.02922', '0.004227', '-0.05945', '-0.01299', '0.0512', '-0.04633', '0.0618', '0.03079', '0.0366', '0.03903', '-0.04205', '-0.05957', '-0.0428', '0.03003', '0.013435', '-0.001207', '-0.01182', '-0.0537', '0.04352', '0.03427', '-0.04807', '0.02086', '0.0409', '-0.013626', '-0.0747', '0.02286', '-0.06036', '0.00311', '0.02296', '-0.05023', '0.009056', '0.1178', '0.05316', '-0.05392', '0.03128', '-0.03802', '0.0972', '0.05624', '0.00233', '-0.03555', '0.00954', '0.02707', '0.07056', '-0.02254', '0.02757', '-0.03452', '-0.06107', '0.0322', '-0.0444', '-0.04486', '-0.06885', '0.046', '0.02016', '-0.0818', '-0.05298', '-0.0508', '0.01897', '0.0971', '-0.01984', '0.046', '0.05136', '-0.04425', '0.003445', '-0.07227', '-0.05756', '0.12006', '-0.008316', '-0.0742', '-0.03104', '-0.0873', '0.01141', '0.05267', '0.04004', '0.02963', '-0.1117', '0.01587', '-0.02504', '0.02023', '-0.013214', '-0.04715', '-0.03833', '0.0605', '0.002447', '-0.08124', '-0.08295', '0.0683', '-0.007595', '0.02422', '0.02122', '-0.1227', '0.04294', '-0.01218', '0.0939', '-0.0231', '0.03802', '0.07227', '0.04565', '0.08997', '-0.03833', '0.006756', '0.0429', '-0.0584', '0.02132', '0.02461', '-0.04144', '0.05408', '-0.03503', '-0.0349', '-0.02928', '0.0915', '-0.04474', '-0.00994', '-0.0688', '-0.00891', '-0.0988', '-0.05487', '0.1217', '-0.01804', '0.04282', '-0.01439', '0.02927', '-0.01332', '0.0357', '-0.006264', '0.004894', '-0.01093', '0.003746', '0.08954', '0.0397', '0.014114', '0.00472', '0.0793', '-0.03836', '-0.01408', '-0.05515', '0.02002', '0.03217', '0.05362', '-0.0673', '0.03029', '0.07355', '0.071', '0.0753', '-0.01755', '0.0085', '-0.03183', '-0.0659', '-0.03336', '0.0073', '-0.001735', '-0.01008', '0.05896', '0.005325', '-0.0853', '-0.0557', '-0.002106', '-0.08936', '0.01921', '-0.04163', '0.04547', '0.0634', '0.01292', '0.0457', '-0.07697', '0.03564', '-0.000986', '-0.02177', '0.02245', '-0.00336', '0.04523', '0.04395', '0.12366', '0.05875', '-0.0579', '0.01331', '-0.02672', '0.01415', '-0.1183', '-0.10944', '0.0648', '0.01013', '-0.00913', '-0.02713', '-0.05356', '-0.05338', '0.04138', '-0.04425', '-0.02502', '0.0858', '-0.08997', '-0.02469']",
 'source': 'uniprot',
 'licence': 'CC BY 4.0',
 'version': '2024_03'}

In [5]:
print(dti)

DatasetDict({
    train: Dataset({
        features: ['drugbank_id', 'uniprot_id', 'known_action', 'activity_value', 'confidence_score', 'direct_interaction', 'disease_efficacy', 'mechanism_of_action', 'pchembl', 'activity_type', 'dgidb_score', 'references', 'mechanism_of_action_type', 'stitch_combined_score', 'source'],
        num_rows: 63496
    })
})

In [6]:
protein_df = proteins["train"].to_pandas()
dti_df = dti["train"].to_pandas()

In [7]:
protein_df.head()

,id,length,mass,organism_name,organism_id,primary_protein_name,protein_names,xref_proteomes,sequence,prott5_embedding,source,licence,version
0,uniprot:P81730,119,12555,Achromobacter lyticus,224,Achromolysin,['Achromolysin'],NaN,AQVGTGPGGNQKIGQYEYGSGGRPFLDVAQSGSTYTFNTTNLTVNL...,"['0.05215', '-0.03632', '-0.0495', '0.02155', ...",uniprot,CC BY 4.0,2024_03
1,uniprot:C5E2Q0,302,34726,Lachancea thermotolerans (strain ATCC 56472 / ...,559295,"Genetic interactor of prohibitin 7, mitochondrial","Genetic interactor of prohibitin 7, mitochondrial",UP000002036: Chromosome H,MLSQYLRKHHLLSRRHQFMRCASQSRSPPRSLLQRQAKRRGEAEAV...,"['-0.02104', '-0.05963', '0.02835', '0.04062',...",uniprot,CC BY 4.0,2024_03
2,uniprot:P80036,314,32936,Flavobacterium sp. (strain SK1022),148444,Endo-beta-N-acetylglucosaminidase,"['Endo-beta-N-acetylglucosaminidase', 'DI-N-ac...",NaN,MQFGIVAAIADGGRTARAGGSVRPPRRPPASHTAWGLPRGRPTGQP...,"['0.02286', '-0.02206', '0.003244', '-0.01869'...",uniprot,CC BY 4.0,2024_03
3,uniprot:P03656,348,39551,Enterobacteria phage M13 (Bacteriophage M13),1977402,Gene 1 protein,"['Gene 1 protein', 'G1P']",UP000002111: Genome,MAVYFVTGKLGSGKTLVSVGKIQDKIVAGCKIATNLDLRLQNLPQV...,"['0.01154', '-0.05603', '0.013176', '0.0528', ...",uniprot,CC BY 4.0,2024_03
4,uniprot:Q0BWM9,713,76422,Hyphomonas neptunium (strain ATCC 15444),228405,Polyribonucleotide nucleotidyltransferase,"['Polyribonucleotide nucleotidyltransferase', ...",UP000001959: Chromosome,MFNKQSVSLEWAGRTLTIETGQVARQADGAVMVQYGDTIVLATAVF...,"['0.03354', '0.00636', '-0.002537', '0.0596', ...",uniprot,CC BY 4.0,2024_03

In [8]:
dti_df.head()

,drugbank_id,uniprot_id,known_action,activity_value,confidence_score,direct_interaction,disease_efficacy,mechanism_of_action,pchembl,activity_type,dgidb_score,references,mechanism_of_action_type,stitch_combined_score,source
0,DB00786,A0A0C5PRQ1,NaN,79432.82,9.0,True,True,Matrix metalloproteinase 7 inhibitor,4.10,IC50,NaN,26546217,inhibitor,NaN,ChEMBL
1,DB11651,A0A0G2K344,NaN,5.30,9.0,True,True,PI3-kinase class I inhibitor,8.28,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
2,DB11663,A0A0G2K344,NaN,52.00,9.0,True,True,PI3-kinase class I inhibitor,7.28,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
3,DB11666,A0A0G2K344,NaN,117.00,9.0,True,True,PI3-kinase class I inhibitor,6.93,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
4,DB11759,A0AVT1,NaN,1800.00,9.0,True,True,NEDD8 activating enzyme inhibitor,5.75,IC50,NaN,35131538,inhibitor,NaN,ChEMBL

In [9]:
print(dti_df.columns)
print(dti_df.isna().sum())

Index(['drugbank_id', 'uniprot_id', 'known_action', 'activity_value',
       'confidence_score', 'direct_interaction', 'disease_efficacy',
       'mechanism_of_action', 'pchembl', 'activity_type', 'dgidb_score',
       'references', 'mechanism_of_action_type', 'stitch_combined_score',
       'source'],
      dtype='str')
drugbank_id                     0
uniprot_id                      0
known_action                43080
activity_value              35611
confidence_score            35611
direct_interaction          50559
disease_efficacy            50559
mechanism_of_action         50561
pchembl                     33649
activity_type               33649
dgidb_score                 40160
references                  15896
mechanism_of_action_type    37621
stitch_combined_score       61153
source                          0
dtype: int64

In [13]:
import pandas as pd
from huggingface_hub import hf_hub_download

path = hf_hub_download(
    repo_id="HUBioDataLab/CROssBARv2-KG",
    filename="edges/CTI.csv",
    repo_type="dataset"
)

cti_df = pd.read_csv(path, dtype=str)
print(cti_df.head())
print(cti_df.columns)
print(cti_df.dtypes)

         chembl pchembl activity_value activity_type assay_chembl  uniprot_id  \
0  CHEMBL271225     NaN            NaN           NaN          NaN  A0A0B4K692
1  CHEMBL294536     NaN            NaN           NaN          NaN  A0A0B4K692
2  CHEMBL294760     NaN            NaN           NaN          NaN  A0A0B4K692
3  CHEMBL303159     NaN            NaN           NaN          NaN  A0A0B4K692
4  CHEMBL304233     NaN            NaN           NaN          NaN  A0A0B4K692

  references confidence_score stitch_combined_score  source
0        NaN              NaN                 707.0  STITCH
1        NaN              NaN                 733.0  STITCH
2        NaN              NaN                 706.0  STITCH
3        NaN              NaN                 767.0  STITCH
4        NaN              NaN                 726.0  STITCH
Index(['chembl', 'pchembl', 'activity_value', 'activity_type', 'assay_chembl',
       'uniprot_id', 'references', 'confidence_score', 'stitch_combined_score',
       'source'],
      dtype='str')
chembl                   str
pchembl                  str
activity_value           str
activity_type            str
assay_chembl             str
uniprot_id               str
references               str
confidence_score         str
stitch_combined_score    str
source                   str
dtype: object

In [14]:
cti_df.head()

,chembl,pchembl,activity_value,activity_type,assay_chembl,uniprot_id,references,confidence_score,stitch_combined_score,source
0,CHEMBL271225,NaN,NaN,NaN,NaN,A0A0B4K692,NaN,NaN,707.0,STITCH
1,CHEMBL294536,NaN,NaN,NaN,NaN,A0A0B4K692,NaN,NaN,733.0,STITCH
2,CHEMBL294760,NaN,NaN,NaN,NaN,A0A0B4K692,NaN,NaN,706.0,STITCH
3,CHEMBL303159,NaN,NaN,NaN,NaN,A0A0B4K692,NaN,NaN,767.0,STITCH
4,CHEMBL304233,NaN,NaN,NaN,NaN,A0A0B4K692,NaN,NaN,726.0,STITCH

In [15]:
dti_df.head()

,drugbank_id,uniprot_id,known_action,activity_value,confidence_score,direct_interaction,disease_efficacy,mechanism_of_action,pchembl,activity_type,dgidb_score,references,mechanism_of_action_type,stitch_combined_score,source
0,DB00786,A0A0C5PRQ1,NaN,79432.82,9.0,True,True,Matrix metalloproteinase 7 inhibitor,4.10,IC50,NaN,26546217,inhibitor,NaN,ChEMBL
1,DB11651,A0A0G2K344,NaN,5.30,9.0,True,True,PI3-kinase class I inhibitor,8.28,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
2,DB11663,A0A0G2K344,NaN,52.00,9.0,True,True,PI3-kinase class I inhibitor,7.28,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
3,DB11666,A0A0G2K344,NaN,117.00,9.0,True,True,PI3-kinase class I inhibitor,6.93,IC50,NaN,35500094,inhibitor,NaN,ChEMBL
4,DB11759,A0AVT1,NaN,1800.00,9.0,True,True,NEDD8 activating enzyme inhibitor,5.75,IC50,NaN,35131538,inhibitor,NaN,ChEMBL