In [1]:
import numpy as np
import pandas as pd

In [2]:
hier_df = pd.read_csv("Disease_hiererchical_edges.csv")
d2d_assoc_df = pd.read_csv("Disease_to_disease_association_edge.csv")
d2d_com_df = pd.read_csv("Disease_to_disease_comorbidity_edge.csv")
d2drug_df = pd.read_csv("Disease_to_drug_edge.csv")

# Hiererchial

In [3]:
hier_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35921 entries, 0 to 35920
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   child_id   35921 non-null  str
 1   parent_id  35921 non-null  str
 2   label      35921 non-null  str
dtypes: str(3)
memory usage: 2.4 MB

In [4]:
hier_df.head()

        child_id      parent_id                 label
0  mondo:0000004  mondo:0002816  disease_is_a_disease
1  mondo:0000005  mondo:0021034  disease_is_a_disease
2  mondo:0000009  mondo:0003847  disease_is_a_disease
3  mondo:0000009  mondo:0002243  disease_is_a_disease
4  mondo:0000009  mondo:0002245  disease_is_a_disease

In [6]:
pd.unique(hier_df["label"])

<ArrowStringArray>
['disease_is_a_disease']
Length: 1, dtype: str

# Disease to Disease Association

In [7]:
d2d_assoc_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70772 entries, 0 to 70771
Data columns (total 5 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   disease_id1                      70772 non-null  str
 1   disease_id2                      70772 non-null  str
 2   disgenet_jaccard_genes_score     49177 non-null  float64
 3   disgenet_jaccard_variants_score  23828 non-null  float64
 4   source                           70772 non-null  str
dtypes: float64(2), str(3)
memory usage: 6.5 MB

In [8]:
d2d_assoc_df.head()

,disease_id1,disease_id2,disgenet_jaccard_genes_score,disgenet_jaccard_variants_score,source
0,MONDO:0000004,MONDO:0001896,NaN,0.1,Disgenet Disease-Disease Variant
1,MONDO:0000004,MONDO:0008300,0.133,NaN,Disgenet Disease-Disease Gene
2,MONDO:0000004,MONDO:0008728,0.115,NaN,Disgenet Disease-Disease Gene
3,MONDO:0000004,MONDO:0010264,0.112,NaN,Disgenet Disease-Disease Gene
4,MONDO:0000004,MONDO:0013400,NaN,0.2,Disgenet Disease-Disease Variant

In [13]:
d2d_assoc_df["source"].value_counts()

source
Disgenet Disease-Disease Gene                                     46944
Disgenet Disease-Disease Variant                                  21595
Disgenet Disease-Disease Gene|Disgenet Disease-Disease Variant     2233
Name: count, dtype: int64

# Disease to Disease Comorbidity

In [14]:
d2d_com_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4263 entries, 0 to 4262
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   disease1  4263 non-null   str
 1   disease2  4263 non-null   str
dtypes: str(2)
memory usage: 175.0 KB

In [15]:
d2d_com_df.head()

        disease1       disease2
0  MONDO:0007033  MONDO:0007781
1  MONDO:0007077  MONDO:0001409
2  MONDO:0007077  MONDO:0007781
3  MONDO:0007077  MONDO:0006805
4  MONDO:0007088  MONDO:0004242

# Disease to Drug

In [16]:
d2drug_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37468 entries, 0 to 37467
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   disease_id  37468 non-null  str
 1   drug_id     37468 non-null  str
 2   max_phase   25308 non-null  float64
 3   pubmed_ids  13101 non-null  str
 4   source      37468 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.6 MB

In [18]:
d2drug_df.head()

,disease_id,drug_id,max_phase,pubmed_ids,source
0,MONDO:0000004,DB00741,NaN,19691511,CTD
1,MONDO:0000004,DB01234,NaN,27941970|7477798,CTD
2,MONDO:0000004,DB01708,NaN,17302879,CTD
3,MONDO:0000022,DB00035,NaN,10569604|11485135|15623917|15977961|16168026|2...,CTD
4,MONDO:0000022,DB00458,NaN,15977961|3153240,CTD

# Other Stuff

In [23]:
g2d_df = pd.read_csv("Gene_to_disease_edge.csv")
org_2d_df = pd.read_csv("Organism_to_disease_edge.csv")
pheno_2d_df = pd.read_csv("Phenotype_to_disease.csv")

/var/folders/m9/bbz2dy595yj36y_mky01dk5h0000gn/T/ipykernel_16544/2206584971.py:1: DtypeWarning: Columns (0: gene_id) have mixed types. Specify dtype option on import or set low_memory=False.
  g2d_df = pd.read_csv("Gene_to_disease_edge.csv")

In [24]:
g2d_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1418653 entries, 0 to 1418652
Data columns (total 14 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   gene_id                         1418653 non-null  object
 1   disease_id                      1418653 non-null  str
 2   opentargets_score               845511 non-null   float64
 3   diseases_confidence_score       21670 non-null    float64
 4   allele_id                       10540 non-null    float64
 5   clinical_significance           10540 non-null    str
 6   review_status                   10540 non-null    float64
 7   variation_id                    10540 non-null    float64
 8   pubmed_ids                      10424 non-null    str
 9   disgenet_gene_disease_score     709855 non-null   float64
 10  disgenet_variant_disease_score  59048 non-null    float64
 11  source                          1418653 non-null  str
 12  variant_source                  65275 non-null    str
 13  dbsnp_id                        65275 non-null    str
dtypes: float64(7), object(1), str(6)
memory usage: 199.1+ MB

In [25]:
g2d_df.head()

,gene_id,disease_id,opentargets_score,diseases_confidence_score,allele_id,clinical_significance,review_status,variation_id,pubmed_ids,disgenet_gene_disease_score,disgenet_variant_disease_score,source,variant_source,dbsnp_id
0,-1,MONDO:0001071,NaN,NaN,188114.0,Pathogenic,2.0,190286.0,25972378|32074998|4544753|18414213|25533962|28...,NaN,NaN,Clinvar,Clinvar,rs-1
1,-1,MONDO:0001586,NaN,NaN,26948.0,Pathogenic,2.0,11909.0,9427149|28492532|23786846|1301941|8401515|9787...,NaN,NaN,Clinvar,Clinvar,rs121965020
2,-1,MONDO:0001982,NaN,NaN,195254.0,Pathogenic,2.0,198093.0,8225311|1885770|23252888|11932991|25741868|215...,NaN,NaN,Clinvar,Clinvar,rs120074118
3,-1,MONDO:0002280,NaN,NaN,30372.0,Pathogenic,2.0,15333.0,9859938|17287491|22975760|49057|22028795|13115...,NaN,NaN,Clinvar,Clinvar,rs334
4,-1,MONDO:0002442,NaN,NaN,23322.0,Pathogenic,2.0,8283.0,19380584|26467025|11756609|15580566|14633633|2...,NaN,NaN,Clinvar,Clinvar,rs116840778

In [26]:
pd.unique(g2d_df["gene_id"])

array([-1, 1, 10, ..., 'Q9Y6Y1', 'Q9Y6Z7', 'W5XKT8'],
      shape=(33415,), dtype=object)

In [27]:
org_2d_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1063 entries, 0 to 1062
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   organism_id  1063 non-null   str
 1   disease_id   1063 non-null   str
 2   label        1063 non-null   str
dtypes: str(3)
memory usage: 77.7 KB

In [28]:
org_2d_df.head()

         organism_id     disease_id                    label
0  ncbitaxon:1674146  mondo:0019632  organism_causes_disease
1   ncbitaxon:138948  mondo:0005791  organism_causes_disease
2   ncbitaxon:499556  mondo:0017878  organism_causes_disease
3     ncbitaxon:1485  mondo:0005767  organism_causes_disease
4     ncbitaxon:5722  mondo:0005135  organism_causes_disease

In [29]:
pd.unique(org_2d_df["label"])

<ArrowStringArray>
['organism_causes_disease']
Length: 1, dtype: str

In [30]:
pheno_2d_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 113228 entries, 0 to 113227
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   hpo_id      113228 non-null  str
 1   disease_id  113228 non-null  str
 2   pubmed_ids  90686 non-null   str
 3   evidence    113228 non-null  str
dtypes: str(4)
memory usage: 7.0 MB

In [31]:
pheno_2d_df.head()

       hpo_id     disease_id pubmed_ids evidence
0  HP:0011097  MONDO:0014916   27476654      PCS
1  HP:0011097  MONDO:0030473   33880529      PCS
2  HP:0011097  MONDO:0044646   27666374      PCS
3  HP:0011097  MONDO:0859283   35830857      PCS
4  HP:0011097  MONDO:0011929        NaN      TAS

In [36]:
from collections import defaultdict

hyperedges = defaultdict(lambda: {
    "disease": None,
    "parents": set(),
    "associated_diseases": set(),
    "comorbidity_diseases": set(),
    "drugs": set(),
    "genes": set(),
    "organisms": set(),
    "phenotypes": set(),
})

In [38]:
## add_edges(dgi_df, disease_col="disease_id", neighbor_col="gene_id", neighbor_type="genes")
add_edges(hier_df,disease_col="child_id",neighbor_col="parent_id",neighbor_type="parents")
add_edges(d2d_assoc_df,disease_col="disease_id1",neighbor_col="disease_id2",neighbor_type="associated_diseases")
add_edges(d2d_assoc_df,disease_col="disease_id2",neighbor_col="disease_id1",neighbor_type="associated_diseases")
add_edges(d2d_com_df,disease_col="disease1",neighbor_col="disease2",neighbor_type="comorbidity_diseases")
add_edges(d2d_com_df,disease_col="disease2",neighbor_col="disease1",neighbor_type="comorbidity_diseases")
add_edges(d2drug_df,disease_col="disease_id",neighbor_col="drug_id",neighbor_type="drugs")
add_edges(g2d_df,disease_col="disease_id",neighbor_col="gene_id",neighbor_type="genes")
add_edges(org_2d_df,disease_col="disease_id",neighbor_col="organism_id",neighbor_type="organisms")
add_edges(pheno_2d_df,disease_col="disease_id",neighbor_col="hpo_id",neighbor_type="phenotypes")

In [53]:
hyperedge_df = pd.DataFrame(hyperedges).T

In [54]:
hyperedge_df.info()

<class 'pandas.DataFrame'>
Index: 38594 entries, mondo:0000004 to MONDO:0008216
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   disease               38594 non-null  object
 1   parents               38594 non-null  object
 2   associated_diseases   38594 non-null  object
 3   comorbidity_diseases  38594 non-null  object
 4   drugs                 38594 non-null  object
 5   genes                 38594 non-null  object
 6   organisms             38594 non-null  object
 7   phenotypes            38594 non-null  object
dtypes: object(8)
memory usage: 3.1+ MB

In [59]:
hyperedge_df[:100]

,disease,parents,associated_diseases,comorbidity_diseases,drugs,genes,organisms,phenotypes
mondo:0000004,mondo:0000004,{mondo:0002816},{},{},{},{},{},{}
mondo:0000005,mondo:0000005,{mondo:0021034},{},{},{},{},{},{}
mondo:0000009,mondo:0000009,"{mondo:0003847, mondo:0002245, mondo:0002243}",{},{},{},{},{},{}
mondo:0000014,mondo:0000014,{mondo:0001703},{},{},{},{},{},{}
mondo:0000015,mondo:0000015,{mondo:0003832},{},{},{},{},{},{}
...,...,...,...,...,...,...,...,...
mondo:0000245,mondo:0000245,{mondo:0001461},{},{},{},{},{},{}
mondo:0000248,mondo:0000248,{mondo:0005358},{},{},{},{},"{ncbitaxon:11053, ncbitaxon:11060, ncbitaxon:1...",{}
mondo:0000249,mondo:0000249,{mondo:0001673},{},{},{},{},{},{}
mondo:0000250,mondo:0000250,{mondo:0045030},{},{},{},{},{},{}
mondo:0000251,mondo:0000251,{mondo:0001673},{},{},{},{},{},{}

In [73]:
tuple_rows = []
arities = []

for _, row in hyperedge_df.iterrows():
    hyperedge = (
        ["DISEASE:" + row["disease"]] +
        ["PARENT_DISEASE:" + str(x) for x in row["parents"]] +
        ["ASSOCIATED_DISEASE:" + str(x) for x in row["associated_diseases"]] +
        ["COMORBID_DISEASE:" + str(x) for x in row["comorbidity_diseases"]] +
        ["DRUG:" + str(x) for x in row["drugs"]] +
        ["GENE:" + str(x) for x in row["genes"]] +
        ["ORGANISM:" + str(x) for x in row["organisms"]] +
        ["PHENOTYPE:" + str(x) for x in row["phenotypes"]]
    )

    tuple_rows.append({
        "relation": "disease_context",
        "nodes": hyperedge,
        "arities":len(hyperedge)
    })

In [74]:
tuple_df = pd.DataFrame(tuple_rows)

In [75]:
tuple_df.head()

          relation                                              nodes  arities
0  disease_context  [DISEASE:mondo:0000004, PARENT_DISEASE:mondo:0...        2
1  disease_context  [DISEASE:mondo:0000005, PARENT_DISEASE:mondo:0...        2
2  disease_context  [DISEASE:mondo:0000009, PARENT_DISEASE:mondo:0...        4
3  disease_context  [DISEASE:mondo:0000014, PARENT_DISEASE:mondo:0...        2
4  disease_context  [DISEASE:mondo:0000015, PARENT_DISEASE:mondo:0...        2

In [76]:
tuple_df["arities"].describe()

count    38594.000000
mean        46.400969
std        285.237567
min          2.000000
25%          2.000000
50%          3.000000
75%         16.000000
max      15545.000000
Name: arities, dtype: float64

In [86]:
tuple_df_preprocessed = tuple_df[tuple_df["arities"] <= 200]

In [87]:
tuple_df_preprocessed["arities"].describe()

count    37201.000000
mean        14.273622
std         27.445766
min          2.000000
25%          2.000000
50%          3.000000
75%         13.000000
max        200.000000
Name: arities, dtype: float64

In [88]:
final_list = tuple_df_preprocessed["nodes"].to_list()

('DISEASE:mondo:0017050',
 'PARENT_DISEASE:mondo:0021220',
 'PARENT_DISEASE:mondo:0005564')

In [90]:
len(final_list)

37201

In [96]:
with open("disease_context_hyperedges.txt", "w") as f:
    f.write("\n".join([str(tuple(l))for l in final_list]))